### ISSUE TITLE
UPDATE - Make hamburger mobile menu a bit wider and taller

### ISSUE THREAD

**Issue by vincentntang** [TampaDevs/tampadevs-original-site#82]
Here's the current mobile menu if you shrink down the tampa devs site

![image](https://user-images.githubusercontent.com/10290348/225605944-af7a6c1e-58cf-4e29-9bcd-1e2c9d2f4714.png)

We should probably make the hamburger menu a bit wider for people with bigger fingers. Probably make it wider by 80% ish

Likewise, increase the height by maybe 20%

AC
- Make hamburger menu icon bigger so easier to click on.
- do whatever looks good on the site, the suggested values are just suggestions though

**Comment by iamwill123** [comment]
UX-wise, can we make the hamburger on the right side? also noticed this on mobile, if you swipe right.
![IMG_4263](https://user-images.githubusercontent.com/15272175/225714052-92429bb1-12a5-4ea9-9766-614910b1d1c2.PNG)

**Comment by ebanner** [comment]
Seems like PR #83 should close this issue

Pretty sure it didn't automatically close because it says `Link to issue: #82` in the PR, and `Link` is not a keyword that will auto-close an issue from a PR

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
